CREATE TABLE FORECAST (
    ID INT NOT NULL AUTO_INCREMENT
  , CITY VARCHAR(60) NOT NULL
  , SOURCE_NAME VARCHAR(60) NOT NULL
  , REQUEST_DATE DATE NOT NULL
  , FORECAST_DATE DATE NOT NULL
  , TEMPERATURE DOUBLE
  , PRESSURE DOUBLE
  , HUMIDITY DOUBLE
  , WING_SPEED DOUBLE
  , VERSION INT NOT NULL DEFAULT 0
  , PRIMARY KEY (ID)
);
